config/routes.rb
Rails.application.routes.draw do
  # get 'pages/about'

  get '/about', to: 'pages#about'
  # verb '/path', to: 'controller_name#action_name'

  # get 'pages/contact'

  get '/contact', to: 'pages#contact'
  # get '/home', to: 'pages#home'

  root to: 'pages#home'

  get '/restaurants', to: 'restaurants#index'

  post '/restaurants', to: 'restaurants#create'

  get '/restaurants/:id', to: 'restaurants#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
  }

  def index
    # raise !!! first thing that you do to make sure the params are passing
    # if there is a filter
    #   display the right info with the right category
    # else
    #   display all
    # end
    @category = params[:category]
    if @category.present?
      @restaurants = RESTAURANTS.select do |id, resto|
        resto[:category] == @category
      end
    else
      @restaurants = RESTAURANTS
    end
  end

  def create
    # raise
    render plain: "your restaurant is #{params[:name]} and is in #{params[:address]}"
  end

  def show
    # raise
    @resto = RESTAURANTS[params["id"].to_i]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lecture01Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>This is my navbar</h1>
    <%= yield %>
    <p>footer</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<h2>Hello Oslo!</h2>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>homepage</h1>

<h2>GET REQUEST TO FILTER</h2>
<!-- form action="/url" method="verb" -->
<form action="/restaurants" method="get">
  <input type="text" name="category" placeholder="What kind of food?">
  <input type="submit">
</form>


<!-- params["category"]
params[:category] -->


<h2>POST REQUEST TO CREATE A RESTO</h2>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>My all restaurants</h1>

<% @restaurants.each do |id, resto| %>
  <h2><%= resto[:name] %></h2>
  <p><%= resto[:address] %></p>
  <p><%= resto[:category] %></p>

<% end %>

app/views/restaurants/show.html.erb
<%= @resto[:name] %>

<%#= link_to "text to the user", prefix_path %>

<%= link_to "all the restos", restaurants_path %>